# Generated by Django 4.0.3 on 2022-03-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0010_bluray_amazon_aff_link'),
        ('people', '0007_people_slug'),
        ('profiles', '0003_alter_favoritemovie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritebluray',
            name='blu_ray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_bluray', to='blurays.bluray'),
        ),
        migrations.AlterField(
            model_name='favoritepeople',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_people', to='people.people'),
        ),
    ]
