# Generated by Django 4.0.3 on 2022-04-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0010_bluray_amazon_aff_link'),
        ('profiles', '0004_alter_favoritebluray_blu_ray_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritebluray',
            name='blu_ray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_bluray', to='blurays.bluray'),
        ),
    ]
