# Generated by Django 4.0.3 on 2022-04-02 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blurays', '0012_alter_bluray_request'),
        ('profiles', '0006_remove_favoritebluray_bluray_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritebluray',
            old_name='blu_ray',
            new_name='bluray',
        ),
        migrations.AlterUniqueTogether(
            name='favoritebluray',
            unique_together={('user', 'bluray')},
        ),
    ]
