# Generated by Django 4.0.3 on 2022-03-27 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_link', models.URLField()),
                ('imdb_id', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('1', 'Créé'), ('2', 'Accepté'), ('3', 'Refusé'), ('4', 'Indéterminé')], max_length=56)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
