# Generated by Django 4.0.3 on 2022-03-27 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplerequest',
            options={'verbose_name': "Demande d'ajout - Personnalité", 'verbose_name_plural': "Demandes d'ajout - Personnalité"},
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_user_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovieRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_link', models.URLField()),
                ('imdb_id', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('1', 'Créé'), ('2', 'Accepté'), ('3', 'Refusé'), ('4', 'Indéterminé')], max_length=56)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_user_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'ajout - Film",
                'verbose_name_plural': "Demandes d'ajout - Film",
            },
        ),
        migrations.CreateModel(
            name='BluRayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_link', models.URLField()),
                ('asin', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('1', 'Créé'), ('2', 'Accepté'), ('3', 'Refusé'), ('4', 'Indéterminé')], max_length=56)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluray_user_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'ajout - Blu-Ray",
                'verbose_name_plural': "Demandes d'ajout - Blu-Ray",
            },
        ),
    ]
