# Generated by Django 4.0.3 on 2022-03-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_alter_peoplerequest_options_alter_peoplerequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurayrequest',
            name='amazon_link',
            field=models.URLField(verbose_name='Lien Amazon'),
        ),
        migrations.AlterField(
            model_name='movierequest',
            name='imdb_link',
            field=models.URLField(verbose_name='Lien IMDB'),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='imdb_link',
            field=models.URLField(verbose_name='Lien IMDB'),
        ),
    ]
