# Generated by Django 4.0.3 on 2022-03-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0004_alter_blurayrequest_asin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blurayrequest',
            options={'verbose_name': 'Ajout - Blu-Ray', 'verbose_name_plural': 'Ajouts - Blu-Rays'},
        ),
        migrations.AlterModelOptions(
            name='movierequest',
            options={'verbose_name': 'Ajout - Film', 'verbose_name_plural': 'Ajouts - Films'},
        ),
        migrations.AlterModelOptions(
            name='peoplerequest',
            options={'verbose_name': 'Ajout - Personnalité', 'verbose_name_plural': 'Ajouts - Personnalités'},
        ),
        migrations.AlterField(
            model_name='blurayrequest',
            name='status',
            field=models.CharField(choices=[('1', 'Reçue'), ('2', 'Acceptée'), ('3', 'Refusée'), ('4', 'Indéterminée')], max_length=56),
        ),
        migrations.AlterField(
            model_name='movierequest',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movierequest',
            name='status',
            field=models.CharField(choices=[('1', 'Reçue'), ('2', 'Acceptée'), ('3', 'Refusée'), ('4', 'Indéterminée')], max_length=56),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='status',
            field=models.CharField(choices=[('1', 'Reçue'), ('2', 'Acceptée'), ('3', 'Refusée'), ('4', 'Indéterminée')], max_length=56),
        ),
    ]
