# Generated by Django 4.0.3 on 2022-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0008_alter_blurayrequest_status_alter_dealrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealrequest',
            name='bluray_exists',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
