# Generated by Django 4.0.3 on 2022-04-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0013_remove_bluray_request'),
        ('user_requests', '0009_dealrequest_bluray_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealrequest',
            name='bluray_exists',
        ),
        migrations.AddField(
            model_name='dealrequest',
            name='bluray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blurays.bluray'),
        ),
    ]
