# Generated by Django 4.0.3 on 2022-04-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0010_remove_dealrequest_bluray_exists_dealrequest_bluray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurayrequest',
            name='status',
            field=models.CharField(choices=[('1', 'En-cours'), ('2', 'Acceptée'), ('3', 'Refusée'), ('4', 'Indéterminée')], default='1', max_length=56),
        ),
        migrations.AlterField(
            model_name='dealrequest',
            name='status',
            field=models.CharField(choices=[('1', 'En-cours'), ('2', 'Acceptée'), ('3', 'Refusée'), ('4', 'Indéterminée')], default='1', max_length=56),
        ),
        migrations.AlterField(
            model_name='movierequest',
            name='status',
            field=models.CharField(choices=[('1', 'En-cours'), ('2', 'Acceptée'), ('3', 'Refusée'), ('4', 'Indéterminée')], default='1', max_length=56),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='status',
            field=models.CharField(choices=[('1', 'En-cours'), ('2', 'Acceptée'), ('3', 'Refusée'), ('4', 'Indéterminée')], default='1', max_length=56),
        ),
    ]
