# Generated by Django 4.0.3 on 2022-04-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0011_alter_blurayrequest_status_alter_dealrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blurayrequest',
            options={'verbose_name': 'Demande - Blu-Ray', 'verbose_name_plural': 'Demandes - Blu-Rays'},
        ),
        migrations.AlterModelOptions(
            name='dealrequest',
            options={'verbose_name': 'Demande - Bon Plan', 'verbose_name_plural': 'Demande - Bons Plans'},
        ),
        migrations.AlterModelOptions(
            name='movierequest',
            options={'verbose_name': 'Demande - Film', 'verbose_name_plural': 'Demandes - Films'},
        ),
        migrations.AlterModelOptions(
            name='peoplerequest',
            options={'verbose_name': 'Demande - Personnalité', 'verbose_name_plural': 'Demandes - Personnalités'},
        ),
    ]
