# Generated by Django 4.0.3 on 2022-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0014_movierequest_release_year_movierequest_title_vf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierequest',
            name='title_vf',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
    ]
