# Generated by Django 4.0.3 on 2022-04-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0015_alter_movierequest_title_vf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierequest',
            name='title_vf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
