# Generated by Django 4.0.3 on 2022-04-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0020_bluray_forced_sub_bluray_vf'),
        ('user_requests', '0017_blurayrequest_bluray_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurayrequest',
            name='bluray_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_bluray', to='blurays.bluray'),
        ),
    ]
