# Generated by Django 4.0.3 on 2022-04-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0018_alter_blurayrequest_bluray_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blurayrequest',
            old_name='bluray_id',
            new_name='bluray',
        ),
    ]
