# Generated by Django 4.0.3 on 2022-04-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_remove_deal_request'),
        ('user_requests', '0020_movierequest_movie_peoplerequest_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealrequest',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.deal'),
        ),
    ]
