# Generated by Django 4.0.3 on 2022-04-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0021_dealrequest_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluRayRequestOpen',
            fields=[
            ],
            options={
                'verbose_name': 'A traiter - Blu-Ray',
                'verbose_name_plural': 'A traiter - Blu-Rays',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_requests.blurayrequest',),
        ),
        migrations.CreateModel(
            name='DealRequestOpen',
            fields=[
            ],
            options={
                'verbose_name': 'A traiter - Bon plan',
                'verbose_name_plural': 'A traiter - Bons plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_requests.dealrequest',),
        ),
        migrations.CreateModel(
            name='MovieRequestOpen',
            fields=[
            ],
            options={
                'verbose_name': 'A traiter - Film',
                'verbose_name_plural': 'A traiter - Films',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_requests.movierequest',),
        ),
        migrations.CreateModel(
            name='PeopleRequestOpen',
            fields=[
            ],
            options={
                'verbose_name': 'A traiter - Personnalité',
                'verbose_name_plural': 'A traiter - Personnalités',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_requests.peoplerequest',),
        ),
        migrations.AlterModelOptions(
            name='blurayrequest',
            options={'verbose_name': 'Traité - Blu-Ray', 'verbose_name_plural': 'Traité - Blu-Rays'},
        ),
        migrations.AlterModelOptions(
            name='dealrequest',
            options={'verbose_name': 'Traité - Bon Plan', 'verbose_name_plural': 'Traité - Bons Plans'},
        ),
        migrations.AlterModelOptions(
            name='movierequest',
            options={'verbose_name': 'Traité - Film', 'verbose_name_plural': 'Traité - Films'},
        ),
        migrations.AlterModelOptions(
            name='peoplerequest',
            options={'verbose_name': 'Traité - Personnalité', 'verbose_name_plural': 'Traité - Personnalités'},
        ),
    ]
