# Generated by Django 4.0.3 on 2022-03-23 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blurays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Actif'), ('2', 'Expiré'), ('3', 'Indéterminé')], max_length=56)),
                ('price', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bluray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_movie', to='blurays.bluray')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
