# Generated by Django 4.0.3 on 2022-03-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Bon Plan', 'verbose_name_plural': 'Bons Plans'},
        ),
    ]
