# Generated by Django 4.0.3 on 2022-03-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0010_bluray_amazon_aff_link'),
        ('deals', '0002_alter_deal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amazon_link',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='bluray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_movie', to='blurays.bluray'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Actif'), ('2', 'Expiré'), ('3', 'Indéterminé')], max_length=56, null=True),
        ),
    ]
