# Generated by Django 4.0.3 on 2022-03-28 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0010_bluray_amazon_aff_link'),
        ('deals', '0003_deal_amazon_link_alter_deal_blu_ray_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amazon_link',
            field=models.URLField(verbose_name='Lien Amazon'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='bluray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_bluray', to='blurays.bluray'),
        ),
    ]
