# Generated by Django 4.0.3 on 2022-04-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0008_alter_blurayrequest_status_alter_dealrequest_status_and_more'),
        ('deals', '0005_alter_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_request', to='user_requests.dealrequest'),
        ),
    ]
