# Generated by Django 4.0.3 on 2022-04-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_deal_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='bluray',
            new_name='bluray',
        ),
    ]
