# Generated by Django 4.0.3 on 2022-04-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_alter_deal_bluray'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='amazon_link',
            new_name='amazon_aff_link',
        ),
    ]
