# Generated by Django 4.0.3 on 2022-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_rename_amazon_link_deal_amazon_aff_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='bluray_image',
            field=models.ImageField(blank=True, null=True, upload_to='blurays/'),
        ),
    ]
