# Generated by Django 4.0.3 on 2022-04-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_deal_bluray_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='bluray_image',
        ),
    ]
