# Generated by Django 4.0.3 on 2022-04-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_remove_deal_bluray_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='request',
        ),
    ]
