# Generated by Django 4.0.3 on 2022-04-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_remove_deal_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='created_by',
            new_name='requested_by',
        ),
    ]
