version: 2.1

description: Workflow de build, test, linting, conteneurisation et déploiement.

display:
  source_url: https://github.com/jpvincent1980/bloodeal

orbs:
  python: circleci/python@0.3.2
  docker: circleci/docker@2.0.1
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

  test:
    executor: python/default
    docker:
      - image: cimg/python:3.8.0
        environment:
          ENV: circle
          DATABASE_URL: postgresql://circleci@localhost/circle_test
        auth:
          username: jpvincent1980
          password: $DOCKER_PASSWORD
      - image: cimg/postgres:14.2.0
        environment:
          PGHOST: localhost
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - python/load-cache
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: |
            python -m pytest --co

  lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: python -m flake8

  deploy:
    executor: heroku/default
    steps:
      - checkout
      # Install Heroku if not already installed
      - heroku/install
      # Deploy app to Heroku
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          api-key: HEROKU_API_KEY

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - docker/publish:
          name: containerize
          image: jpvincent1980/bloodeal
          tag: $CIRCLE_SHA1
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - containerize
          filters:
            branches:
              only: main