# Generated by Django 4.0.3 on 2022-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pseudo',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
