# Generated by Django 4.0.3 on 2022-03-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_favoriteuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteUser',
        ),
    ]
