# Generated by Django 4.0.3 on 2022-03-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
                ('amazon_asin', models.CharField(blank=True, max_length=10, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('bluray_image', models.ImageField(blank=True, null=True, upload_to='blurays/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluray_movie', to='movies.movie')),
            ],
        ),
    ]
