# Generated by Django 4.0.3 on 2022-03-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bluray',
            options={'verbose_name': 'Blu-Ray'},
        ),
    ]
