# Generated by Django 4.0.3 on 2022-03-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_alter_peoplerequest_options_alter_peoplerequest_user_and_more'),
        ('blurays', '0002_alter_bluray_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_requests.blurayrequest'),
        ),
    ]
