# Generated by Django 4.0.3 on 2022-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0003_bluray_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='slug',
            field=models.SlugField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
