# Generated by Django 4.0.3 on 2022-03-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0006_alter_bluray_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluray',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
