# Generated by Django 4.0.3 on 2022-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0008_remove_bluray_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
