# Generated by Django 4.0.3 on 2022-04-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_imdb_id'),
        ('blurays', '0010_bluray_amazon_aff_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluray',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bluray_movie', to='movies.movie'),
        ),
    ]
