# Generated by Django 4.0.3 on 2022-04-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0008_alter_blurayrequest_status_alter_dealrequest_status_and_more'),
        ('blurays', '0011_alter_bluray_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluray',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bluray_request', to='user_requests.blurayrequest'),
        ),
    ]
