# Generated by Django 4.0.3 on 2022-04-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0012_alter_bluray_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bluray',
            name='request',
        ),
    ]
