# Generated by Django 4.0.3 on 2022-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0014_bluray_uhd'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
