# Generated by Django 4.0.3 on 2022-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0015_bluray_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='forced_sub',
            field=models.SmallIntegerField(blank=True, choices=[('1', 'Oui'), ('2', 'Non'), ('3', 'Indéterminé')], null=True),
        ),
        migrations.AddField(
            model_name='bluray',
            name='vf',
            field=models.SmallIntegerField(blank=True, choices=[('1', 'Oui'), ('2', 'Non'), ('3', 'Indéterminé')], null=True),
        ),
    ]
