# Generated by Django 4.0.3 on 2022-04-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0016_bluray_forced_sub_bluray_vf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluray',
            name='amazon_asin',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
