# Generated by Django 4.0.3 on 2022-04-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blurays', '0017_alter_bluray_amazon_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bluray_requested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
