# Generated by Django 4.0.3 on 2022-04-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0018_bluray_requested_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bluray',
            name='forced_sub',
        ),
        migrations.RemoveField(
            model_name='bluray',
            name='vf',
        ),
    ]
