# Generated by Django 4.0.3 on 2022-04-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurays', '0019_remove_bluray_forced_sub_remove_bluray_vf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='forced_sub',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bluray',
            name='vf',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
