# Generated by Django 4.0.3 on 2022-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('imdb_id', models.CharField(blank=True, max_length=7, null=True)),
                ('people_image', models.ImageField(blank=True, null=True, upload_to='people/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
