# Generated by Django 4.0.3 on 2022-03-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Personnalité', 'verbose_name_plural': 'Personnalités'},
        ),
    ]
