# Generated by Django 4.0.3 on 2022-03-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0001_initial'),
        ('people', '0002_alter_people_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_requests.peoplerequest'),
        ),
    ]
