# Generated by Django 4.0.3 on 2022-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_people_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='slug',
            field=models.SlugField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
