# Generated by Django 4.0.3 on 2022-03-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_people_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='slug',
        ),
    ]
