# Generated by Django 4.0.3 on 2022-03-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_remove_people_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
