# Generated by Django 4.0.3 on 2022-04-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_people_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de décès'),
        ),
    ]
