# Generated by Django 4.0.3 on 2022-04-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_people_death_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='request',
        ),
    ]
