# Generated by Django 4.0.3 on 2022-04-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_remove_people_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
