# Generated by Django 4.0.3 on 2022-03-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Film'},
        ),
        migrations.AlterModelOptions(
            name='movieactor',
            options={'verbose_name': 'Acteur par film', 'verbose_name_plural': 'Acteurs par film'},
        ),
        migrations.AlterModelOptions(
            name='moviedirector',
            options={'verbose_name': 'Réalisateur par film', 'verbose_name_plural': 'Réalisateurs par film'},
        ),
    ]
