# Generated by Django 4.0.3 on 2022-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
