# Generated by Django 4.0.3 on 2022-04-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_title_vf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='request',
        ),
    ]
