# Generated by Django 4.0.3 on 2022-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_vf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_vo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
