# Generated by Django 4.0.3 on 2022-04-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_people_requested_by'),
        ('movies', '0013_movie_requested_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieactor',
            unique_together={('movie', 'actor')},
        ),
        migrations.AlterUniqueTogether(
            name='moviedirector',
            unique_together={('movie', 'director')},
        ),
    ]
